module OnixParser
  module Codelists
    module Issue47
      LIST_83 = {
        "ALV" => "Alberto Vaccari",
        "AMP" => "Amplified",
        "ANM" => "Antonio Martini",
        "ASV" => "American Standard",
        "CEB" => "Common English Bible",
        "CEI" => "Conferenza Episcopale Italiana",
        "CEN" => "Conferenza Episcopale Italiana 2008",
        "CEV" => "Contemporary English",
        "CNC" => "Concordata",
        "DDI" => "Diodati",
        "DDN" => "Nuova Diodati",
        "DOU" => "Douay-Rheims",
        "EIN" => "Einheitsübersetzung",
        "ESV" => "English Standard",
        "FBB" => "Biblia (1776)",
        "FRA" => "Raamattu (1933/1938)",
        "FRK" => "Raamattu kansalle",
        "FRM" => "Raamattu (1992)",
        "GDW" => "God’s Word",
        "GEN" => "Geneva",
        "GNB" => "Good News",
        "GPR" => "Galbiati, Penna, Rossano – UTET",
        "GRK" => "Original Greek",
        "GRM" => "Garofano, Rinaldi – Marietti",
        "HBR" => "Original Hebrew",
        "HCS" => "Holman Christian Standard",
        "ICB" => "International Children’s",
        "ILC" => "Traduzione Interconfessionale in Lingua Corrente",
        "JER" => "Jerusalem",
        "KJV" => "King James",
        "KJT" => "21st Century King James",
        "LVB" => "Living Bible",
        "LZZ" => "Luzzi",
        "MSG" => "Message Bible",
        "NAB" => "New American",
        "NAS" => "New American Standard",
        "NAU" => "New American Standard, Updated",
        "NBA" => "Bibelen 1895",
        "NBB" => "Bibelen 1930",
        "NBC" => "Bibelen 1938",
        "NBD" => "Bibelen 1978-85",
        "NBE" => "Bibelen 1978",
        "NBF" => "Bibelen 1985",
        "NBG" => "Bibelen 1988",
        "NBH" => "Bibelen 1978-85/rev. 2005",
        "NBI" => "Bibelen 2011",
        "NCV" => "New Century",
        "NEB" => "New English",
        "NGO" => "Bibelen Guds ord",
        "NIV" => "New International",
        "NIR" => "New International Reader’s",
        "NJB" => "New Jerusalem",
        "NKJ" => "New King James",
        "NNK" => "Bibelen, nynorsk",
        "NLV" => "New Living",
        "NRS" => "New Revised Standard",
        "NTV" => "Nueva Traduccion Vivienta",
        "NVB" => "Novissima Versione della Bibbia",
        "NVD" => "Nueva Biblia al Dia",
        "NVI" => "Nueva Version Internacional",
        "PHP" => "New Testament in Modern English (Phillips)",
        "REB" => "Revised English",
        "REV" => "Revised Version",
        "RSV" => "Revised Standard",
        "RVL" => "Reina Valera",
        "SBB" => "Bibel 2000",
        "SMK" => "Bibelen, samisk",
        "TEV" => "Today’s English",
        "TNI" => "Today’s New International",
        "ZZZ" => "Other"
      }
    end
  end
end