module OnixParser
  module Codelists
    module Issue47
      LIST_158 = {
        "01" => "Front cover",
        "02" => "Back cover",
        "03" => "Cover / pack",
        "04" => "Contributor picture",
        "05" => "Series image / artwork",
        "06" => "Series logo",
        "07" => "Product image / artwork",
        "08" => "Product logo",
        "09" => "Publisher logo",
        "10" => "Imprint logo",
        "11" => "Contributor interview",
        "12" => "Contributor presentation",
        "13" => "Contributor reading",
        "14" => "Contributor event schedule",
        "15" => "Sample content",
        "16" => "Widget",
        "17" => "Review",
        "18" => "Other commentary / discussion",
        "19" => "Reading group guide",
        "20" => "Teacher’s guide",
        "21" => "Feature article",
        "22" => "Character ‘interview’",
        "23" => "Wallpaper / screensaver",
        "24" => "Press release",
        "25" => "Table of contents",
        "26" => "Trailer",
        "27" => "Cover thumbnail",
        "28" => "Full content",
        "29" => "Full cover",
        "30" => "Master brand logo",
        "31" => "Description",
        "32" => "Index",
        "33" => "Student’s guide",
        "34" => "Publisher’s catalogue",
        "35" => "Online advertisement panel",
        "36" => "Online advertisement page",
        "37" => "Promotional event material",
        "38" => "Digital review copy",
        "39" => "Instructional material",
        "40" => "Errata",
        "41" => "Introduction",
        "42" => "Collection description",
        "43" => "Bibliography",
        "44" => "Abstract",
        "45" => "Cover holding image",
        "99" => "License"
      }
    end
  end
end